# Generated by Django 5.1.6 on 2025-02-26 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('conversation_id', models.CharField(max_length=255, unique=True)),
                ('conversation_state', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('conversation_id', models.CharField(max_length=255)),
                ('conversation_direction', models.CharField(choices=[('SENT', 'SENT'), ('RECEIVED', 'RECEIVED')], max_length=8)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
