# Generated by Django 5.1.6 on 2025-02-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_message_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='conversation_direction',
            new_name='message_type',
        ),
        migrations.RemoveField(
            model_name='message',
            name='type',
        ),
        migrations.AlterField(
            model_name='conversation',
            name='conversation_state',
            field=models.CharField(max_length=10),
        ),
    ]
